### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by mariia-zelenskaia** [mariia-zelenskaia/transannot#1]
- [ ] think about parameters
- [ ] fix the problem with a pathway to mmseqs
- [ ] fork mmseqs separately to lib
- [ ] read about httpie and probably implement HTTP client to get GO IDs
- [ ] think how to ask the user whether transcriptome is assembled or not
